services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"  # API - Fixed port
      - "9001:9001"  # Console - Fixed port
    command: server --console-address ":9001" /data
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
    depends_on:
      - postgres
      - minio  # Added minio dependency
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myapp
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      MINIO_ENDPOINT: http://minio:9000  # Added MinIO config
      JWT_SECRET: your-secret-key-change-this  # Added JWT secret
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - app-network

volumes:
  postgres-data:
  minio-data:

networks:
  app-network:
    driver: bridge